# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connected_users.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63onnected_users.proto\x12\x0f\x63onnected_users\"L\n\x04User\x12\x10\n\x08username\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\r\x12\x18\n\x10joined_timestamp\x18\x04 \x01(\x04\"6\n\x0e\x43onnectedUsers\x12$\n\x05users\x18\x01 \x03(\x0b\x32\x15.connected_users.User')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'connected_users_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USER._serialized_start=42
  _USER._serialized_end=118
  _CONNECTEDUSERS._serialized_start=120
  _CONNECTEDUSERS._serialized_end=174
# @@protoc_insertion_point(module_scope)
